install: make get-deps
./configure && make && make test
language: cpp
script: scons
compiler: clang
compiler:
  - clang++
  - g++
  before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
